custom_profile_link_user_field_ids:
  type: list
  default: "1|"
  description: The id(s) of your custom user field(s), e.g. 1, 2, etc.

custom_profile_link_labels:
  type: list
  default: "View external profile|"
  description: The label(s) to add to the user's profile page, e.g. View external profile

custom_profile_link_prefixes:
  type: list
  default: "https://yoursite.com/users/|"
  description: Optional text(s) to prepend before the user field value, e.g. https://yoursite.com/users/

custom_profile_link_debug_mode:
  type: bool
  default: false
  description: Enables logging debug information, e.g. "Script Loaded", User fields, etc
